#!/bin/bash

echo "CRED_PATH=/etc/nginx/certs" > "srcs/.env"
echo "CRED_CERT=nginx-selfsigned.crt" >> "srcs/.env"
echo "CRED_KEY=nginx-selfsigned.key" >> "srcs/.env"
echo >> "srcs/.env"
echo "COUNTRY=ES" >> "srcs/.env"
echo "STATE=42MADRID" >> "srcs/.env"
echo "LOCALITY=42MADRID" >> "srcs/.env"
echo "ORGANIZATION=42MADRID" >> "srcs/.env"
echo "ORG_UNIT=42MADRID" >> "srcs/.env"
echo "COMMON_NAME=danfern3.42.fr" >> "srcs/.env"
echo "DB_NAME=dbsite" >> "srcs/.env"
echo "DB_USER=dbuser" >> "srcs/.env"
echo "DB_PASSWORD=123456789" >> "srcs/.env"
echo "DB_HOST=mariadb" >> "srcs/.env"
echo "DB_SCRIPT_SQL=/etc/mysql/init.sql" >> "srcs/.env"
echo "WP_DOMAIN=danfern3.42.fr" >> "srcs/.env"
echo "WP_TITLE=inception" >> "srcs/.env"
echo "WP_ADMIN_USER=danfern3" >> "srcs/.env"
echo "WP_ADMIN_PASSWORD=1234567890" >> "srcs/.env"
echo "WP_ADMIN_EMAIL=danfern3@42.com" >> "srcs/.env"
echo "WP_GUEST_USER=guest" >> "srcs/.env"
echo "WP_GUEST_PASSWORD=123456789" >> "srcs/.env"
echo "WP_GUEST_EMAIL=guest@42.com" >> "srcs/.env"

echo "✔ .env"
